apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  selector:
    app: tetris
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
      nodePort: 30009  # Optional: You can specify or let Kubernetes choose
  type: NodePort
